// Mocks generated by Mockito 5.4.6 from annotations
// in luckify/test/get_fortune_reading_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:luckify/core/utils/uuid_generator.dart' as _i6;
import 'package:luckify/domain/entity/request_entity.dart' as _i5;
import 'package:luckify/domain/entity/response_entity.dart' as _i2;
import 'package:luckify/domain/repository/fortune_repository.dart' as _i3;
import 'package:luckify/presentation/formatters/fortune_content_formatter.dart'
    as _i9;
import 'package:luckify/presentation/prompt/resolvers/prompt_resolver.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseEntity_0 extends _i1.SmartFake
    implements _i2.ResponseEntity {
  _FakeResponseEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FortuneRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFortuneRepository extends _i1.Mock implements _i3.FortuneRepository {
  MockFortuneRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseEntity> fetchFortuneFromAPI(
    _i5.RequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFortuneFromAPI, [request]),
            returnValue: _i4.Future<_i2.ResponseEntity>.value(
              _FakeResponseEntity_0(
                this,
                Invocation.method(#fetchFortuneFromAPI, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ResponseEntity>);
}

/// A class which mocks [UuidGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuidGenerator extends _i1.Mock implements _i6.UuidGenerator {
  MockUuidGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generate() =>
      (super.noSuchMethod(
            Invocation.method(#generate, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generate, []),
            ),
          )
          as String);
}

/// A class which mocks [PromptResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromptResolver extends _i1.Mock implements _i8.PromptResolver {
  MockPromptResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String resolvePrompt(_i5.RequestEntity? request) =>
      (super.noSuchMethod(
            Invocation.method(#resolvePrompt, [request]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#resolvePrompt, [request]),
            ),
          )
          as String);
}

/// A class which mocks [FortuneContentFormatter].
///
/// See the documentation for Mockito's code generation for more information.
class MockFortuneContentFormatter extends _i1.Mock
    implements _i9.FortuneContentFormatter {
  MockFortuneContentFormatter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String format(String? content, _i5.RequestEntity? request) =>
      (super.noSuchMethod(
            Invocation.method(#format, [content, request]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#format, [content, request]),
            ),
          )
          as String);
}
