// Mocks generated by Mockito 5.4.6 from annotations
// in luckify/test/fortune_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:luckify/data/dto/request_dto.dart' as _i3;
import 'package:luckify/data/dto/response_dto.dart' as _i5;
import 'package:luckify/data/mapper/request_mapper.dart' as _i10;
import 'package:luckify/data/mapper/response_mapper.dart' as _i11;
import 'package:luckify/data/network/base_api.dart' as _i8;
import 'package:luckify/data/network/network_client_interface.dart' as _i7;
import 'package:luckify/domain/entity/request_entity.dart' as _i4;
import 'package:luckify/domain/entity/response_entity.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequestDTO_1 extends _i1.SmartFake implements _i3.RequestDTO {
  _FakeRequestDTO_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequestEntity_2 extends _i1.SmartFake implements _i4.RequestEntity {
  _FakeRequestEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponseDTO_3 extends _i1.SmartFake implements _i5.ResponseDTO {
  _FakeResponseDTO_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponseEntity_4 extends _i1.SmartFake
    implements _i6.ResponseEntity {
  _FakeResponseEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkClientInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkClientInterface extends _i1.Mock
    implements _i7.NetworkClientInterface {
  MockNetworkClientInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> send<T>({
    required _i8.BaseApi? api,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#send, [], {#api: api, #fromJson: fromJson}),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#send, [], {
                      #api: api,
                      #fromJson: fromJson,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#send, [], {
                    #api: api,
                    #fromJson: fromJson,
                  }),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [RequestMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestMapper extends _i1.Mock implements _i10.RequestMapper {
  MockRequestMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RequestDTO toDTO(_i4.RequestEntity? entity) =>
      (super.noSuchMethod(
            Invocation.method(#toDTO, [entity]),
            returnValue: _FakeRequestDTO_1(
              this,
              Invocation.method(#toDTO, [entity]),
            ),
          )
          as _i3.RequestDTO);

  @override
  _i4.RequestEntity toEntity(_i3.RequestDTO? dto) =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, [dto]),
            returnValue: _FakeRequestEntity_2(
              this,
              Invocation.method(#toEntity, [dto]),
            ),
          )
          as _i4.RequestEntity);
}

/// A class which mocks [ResponseMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponseMapper extends _i1.Mock implements _i11.ResponseMapper {
  MockResponseMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ResponseDTO toDTO(_i6.ResponseEntity? entity) =>
      (super.noSuchMethod(
            Invocation.method(#toDTO, [entity]),
            returnValue: _FakeResponseDTO_3(
              this,
              Invocation.method(#toDTO, [entity]),
            ),
          )
          as _i5.ResponseDTO);

  @override
  _i6.ResponseEntity toEntity(_i5.ResponseDTO? dto) =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, [dto]),
            returnValue: _FakeResponseEntity_4(
              this,
              Invocation.method(#toEntity, [dto]),
            ),
          )
          as _i6.ResponseEntity);
}
